### ISSUE TITLE
Does this image support Read-Only File System?

### ISSUE THREAD

**Issue by RehanSaeed** [docker-library/redis#109]
I learned that you have the ability to set the file system to [read-only](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v-read-only) in docker by setting a simple boolean flag. Any custom volumes you've specified remain unaffected. This seems like a great little flag to turn on for some added security. Does this image support it, the container seems to run with it turned on?

**Comment by tianon** [comment]
Yep, it should work fine as-is (since we invoke a `VOLUME` for `/data` by default).

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). :+1:
