### ISSUE TITLE
X509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by vodasan** [docker-library/redis#110]
Hi,

I'm trying to create a docker with redis on my ubuntu virtualbox. But I've this error with dockerfile or docker pull command.

Can you help me ?

Best regards

**Comment by tianon** [comment]
This sounds like your clock is out of sync in your VM and/or host machine -- have you tried installing `ntp` in your VM to get the clock in sync?

Since this isn't an issue with the image itself (and is really an issue in environment / hosting), I'm going to close.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). :+1:
