### ISSUE TITLE
Shouldn't we set overcommit_memory=1?

### ISSUE THREAD

**Issue by gastonmorixe** [docker-library/redis#19]
Guys,

There are some official recommended settings here http://redis.io/topics/admin

One should be
`RUN sysctl vm.overcommit_memory=1`

What do you think?

Thanks

**Comment by yosifkit** [comment]
This was discussed in #14.  But I am open to good reasons.

**Comment by tianon** [comment]
It wouldn't be possible to set this via a `RUN` line in the `Dockerfile` -- that won't carry into the image.

Also, I think this sets it system-wide, not just for the container, so I'd be wary of setting this in the entrypoint too (which would be the only place it could possibly even work).

**Comment by imton** [comment]
so, is this a limitation of linux containers?

**Comment by Starefossen** [comment]
:+1: for `RUN sysctl vm.overcommit_memory=1`

**Comment by archr** [comment]
+1 RUN sysctl vm.overcommit_memory=1

**Comment by tianon** [comment]
> so, is this a limitation of linux containers?

Yes.  Some `sysctl` options are scoped to the container, but a large number are read from the host.  On top of that, actually _changing_ their values requires write access to `/proc/sys`, which is impossible by default since `/proc` is read-only inside Docker.  I'm +1 for documenting that folks using this image ought to set this value on their host, but we can't do anything about it inside the container.

**Comment by sebicas** [comment]
Maybe related: https://github.com/boot2docker/boot2docker/issues/1083

**Comment by tianon** [comment]
See also https://github.com/docker/docker/issues/4717 -- there isn't anything we can do from the Docker perspective except document how to set this value on the host (which would go into https://github.com/docker-library/docs/blob/master/redis/content.md; a PR would be awesome).

**Comment by pataquets** [comment]
docker/docker#19265 just merged. Can this solve the issue?

**Comment by tianon** [comment]
Very cool -- that won't make it into 1.11 (being released today), but we could document for users of 1.12+ how they can use `--sysctl` on their `docker run` invocations in order to accomplish this. :+1:

**Comment by justincormack** [comment]
I don't think `vm.overcommit_memory` is a namespaced sysctl, so that will not resolve this issue - it still has to be set globally on the host.

**Comment by tianon** [comment]
@justincormack aww, fair enough -- I suppose that means there's not really much we can do here besides documenting that it's recommended and that it'd have to happen on the Docker host, not in the container :disappointed:

**Comment by bkuhl** [comment]
This isn't a "run a container to solve a problem" kind of thing, but I appreciate there being containers running as part of a stack to help serve as documentation for what's been done to the host.  That said, I believe some folks may find https://github.com/bkuhl/redis-overcommit-on-host useful.

**Comment by yosifkit** [comment]
Thanks for the note @bkuhl.

Closing since this not something that can be changed by the image, especially since we don't want to have users running the redis container with `--priviledged`.

**Comment by beporter** [comment]
If anyone stumbles here trying to solve the Redis docker container warning about vm.overcommit_memory on startup, and happens to be running Rancher Desktop on a Mac (which doesn't utilize `sysctl` on the Mac host, but is irrelevant since Docker is running inside a lima VM anyway) there appears to be a crude workaround possible by telling lima to set the sysctl for the VM. 

Create an `rancher-override.yml` file and either copy it or symlink it to: `$HOME/Library/Application\ Support/rancher-desktop/lima/_config/override.yaml`

```yml
# Symlink this file to:
# `ln -s $PWD/rancher-override.yml $HOME/Library/Application\ Support/rancher-desktop/lima/_config/override.yaml`
provision:
- mode: system
  script: |
    #!/bin/sh
    sysctl -w vm.overcommit_memory=1
```

Just be aware this override applies to **ALL** docker containers running inside the lima VM that's running under the hood of Rancher Desktop, which could cause issues elsewhere.
