### ISSUE TITLE
FATAL CONFIG FILE ERROR  Bad directive or wrong number of arguments

### ISSUE THREAD

**Issue by truptipritish** [docker-library/redis#196]
Hi I have a Dockerfile:
`# Pull base image.
FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y curl
RUN curl --silent --location https://deb.nodesource.com/setup_4.x | sudo bash -
RUN apt-get install --yes nodejs
RUN apt-get install --yes build-essential

COPY . /src

RUN cd /src
RUN npm install -g npm
#RUN npm install

EXPOSE 8080

RUN apt-get update && apt-get install -y redis-server
EXPOSE 6379

RUN apt-get update
RUN \
  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 && \
  echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' > /etc/apt/sources.list.d/mongodb.list && \
  apt-get update && \
  apt-get install -y mongodb-org && \
  rm -rf /var/lib/apt/lists/*

VOLUME ["/data/db"]

WORKDIR /data

EXPOSE 27017
EXPOSE 28017

ADD run.sh /run.sh
RUN chmod +x /run.sh

ENTRYPOINT  ["/usr/bin/redis-server"]
#CMD ["node", "index.js"]
CMD ["/run.sh"]`

**run.sh file:**
`nodaemon=true

command=node index.js

command=mongod`

When I build the Docker file, it gets successfully built.
But, when I try logging in to the image, I get the following error:
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 3
>>> 'command=node index.js'
Bad directive or wrong number of arguments

Please help me solve this issue.

Thanks

**Comment by wglambert** [comment]
Change it to `command="node index.js"` so it's one string, but it gets overwritten on the next line, and that only sets environment variables

Also your `rm -rf /var/lib/apt/lists/*` line should include the `apt-get update`, else the files in `lists/` still gets downloaded as it's part of the `apt update` docker layer

You should ask over at [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability
