### ISSUE TITLE
Disable Transparent Huge Pages (THP) in docker machine 

### ISSUE THREAD

**Issue by eranchetz** [docker-library/redis#20]
We probably need to disable  Transparent Huge Pages (THP) inside the docker machine this might cause latency and memory usage issues with Redis. 
To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'

**Comment by eranchetz** [comment]
see #21, 
I do understand you need to change it in host level, but I assume it needs to be changed in the docker container as well, please correct me if I am wrong.

**Comment by yosifkit** [comment]
Actually this is 100% in the host since it is part of the kernel configuration.  The PR would actually fail on my machine since the `/sys/kernel/mm/transparent_hugepage/` directory does not even exist, and thanks to https://github.com/docker/docker/pull/5445 cannot affect the host machine anyway. 

About `/sys/`
> sysfs is a ram-based filesystem initially based on ramfs. It provides
a means to export kernel data structures, their attributes, and the 
linkages between them to userspace. ([kernel.org](https://www.kernel.org/doc/Documentation/filesystems/sysfs.txt))

Anything done in `/sys/` is outside the filesystem of the docker container and would never be committed to the image.

**Comment by Starefossen** [comment]
Thanks for the clarification @yosifkit
