### ISSUE TITLE
Unable to display anything after running the container

### ISSUE THREAD

**Issue by PVinay737** [docker-library/redis#200]
This is the log I get after `docker-compose up` 

![redislog](https://user-images.githubusercontent.com/44138475/61240828-c1671200-a75f-11e9-96d4-41b42f4778d1.png)

Upon opening `localhost:4000` nothing gets displayed in the browser

Working on 
- https://cube.dev/docs/deployment#docker-compose

**Comment by wglambert** [comment]
Did you [publish](https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose) the port? 

I'd recommend trying the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability

**Comment by PVinay737** [comment]
Was in the same thought @wglambert ! Trying out you mentions as well
