### ISSUE TITLE
docker run --restart always not working with redis

### ISSUE THREAD

**Issue by hiake21c** [docker-library/redis#204]
I just try to run redis with docker. but --restart option is not working with redis docker latest image. 

here is my command which I tried run docker redis 
docker run -p6379:6379 --name redis -d redis redis-server --appendonly yes --restart always

and here is the logs message

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 3
>>> 'restart "always"'
Bad directive or wrong number of arguments

this command worked before. but These days suddenly not working.

here is addtional info which my docker version.

Docker version 19.03.1, build 74b1e89

thanks to looking into this issue.

best regards.

Jongmin Kim.

**Comment by wglambert** [comment]
`Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]`
For the `--restart` option to be passed to Docker it syntactically has to be before the image name, everything after that is interpreted as a command and gets sent to the entrypoint

In the future these types of questions should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability
