### ISSUE TITLE
[Question]: Emulate Redis to Go from Heroku

### ISSUE THREAD

**Issue by SumNeuron** [docker-library/redis#205]
I am a docker noob and am struggling to get my system to work. 
Previously, I tried deploying on Heroku with [Redis To Go](https://devcenter.heroku.com/articles/python-rq#deployment) and it worked with minimal struggle. Now I need to do it myself. 

Assuming I am trying to recreate the MWE in the link above, what do I need to do with the Image to emulate the Redis To Go?

**Comment by wglambert** [comment]
As-is that setup isn't exactly what you'd want in a container environment. All of those workers are expanding the same namespace and resource pool under one supervisor. A proper setup would be to have the workers in individual containers, delegating work to them in that way would mean if any of them encounter errors/issues then it's localized to their one container.

There's a few search results for Python-rq and Docker in google but nothing official. The official recommendation is to use something like systemd for management.
http://python-rq.org/docs/workers/#starting-workers
>You should use process managers like Supervisor or systemd to run RQ workers in production.

So if you wanted to run this setup in a container anyway then you'd probably need something like an init system in a container running Python, and Redis, to then spin up workers in the same container and then link back to Heroku in some way
Also looking at https://elements.heroku.com/addons/redistogo it seems Redis-to-Go is fully managed by Heroku. Not being familiar with them I'm not sure exactly what you yourself could manage outside of their cloud platform.

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
