### ISSUE TITLE
Master is currently unable to PSYNC but should be in the future

### ISSUE THREAD

**Issue by machicolover** [docker-library/redis#209]
I received this log:

`7:S 23 Oct 2019 09:16:16.029 * Connecting to MASTER 127.11.0.2:6379
7:S 23 Oct 2019 09:16:16.029 * MASTER <-> REPLICA sync started
7:S 23 Oct 2019 09:16:16.029 * Non blocking connect for SYNC fired the event.
7:S 23 Oct 2019 09:16:16.029 * Master replied to PING, replication can continue...
7:S 23 Oct 2019 09:16:16.029 * Trying a partial resynchronization (request 0f9dd7a303be57281e7b031cc9e2e744dffd4913:379).
7:S 23 Oct 2019 09:16:16.029 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master`

Please tell me if you need other information. Thank you.

**Comment by wglambert** [comment]
>Can't SYNC while not connected with my master

Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by machicolover** [comment]
@wglambert , here are the configurations I made. Dockerfile is just exposing the port and running the redis service. besides that, I don't think I've run anything else.


[dockercomposeandredisconfigurations.zip](https://github.com/docker-library/redis/files/3765160/dockercomposeandredisconfigurations.zip)

**Comment by wglambert** [comment]
There's an ongoing thread on clustering https://github.com/docker-library/redis/issues/79#issuecomment-268680461
I was able to cluster it just fine here https://github.com/docker-library/redis/issues/190#issuecomment-483345680

Your redis configs should have `cluster-enabled yes` uncommented

For further help you could try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
