### ISSUE TITLE
Uncommon High CPU-Usage 

### ISSUE THREAD

**Issue by Muffl0n-DE** [docker-library/redis#225]
The container uses 100% of the CPU although Redis is not actively used

![image](https://user-images.githubusercontent.com/34190992/74417466-057dda80-4e47-11ea-8b4f-c6aab87a8b9c.png)

Edit:
I´m using redis:alpine

**Comment by itamarhaber** [comment]
Hello @Muffl0n-DE 

This does not look like an issue, but rather misconfiguration. I suspect that the 'kdevtmpfsi' process is a malware/miner that had hijacked your container, perhaps because the Redis server was open to the public without protection. Try removing the container and restarting it with the Redis `requirepass` configuration directive.

**Comment by Muffl0n-DE** [comment]
I also had the thought of the miner.
The only question is how the miner got into the container. The container was only accessible in the local network

**Comment by itamarhaber** [comment]
> The only question is how the miner got into the container. The container was only accessible in the local network.

Evidence would indicate the contrary ;)

**Comment by Muffl0n-DE** [comment]
Damn, it seems to be my Fault. 
Now it works fine.

Thx for the Tip
