### ISSUE TITLE
not able to create redis stream spring boot application 

### ISSUE THREAD

**Issue by mujahid45** [docker-library/redis#238]
Hi, 
I am using redis 5.0.5 and i am trying to use the redis stream. I am unable to create a stream from my spring boot application.  I tested my code,on local redis installed on my computer is working fine and i am able to create the event stream.  same code when i am trying in ocp it is not working. I have tested locally on stream in the container i am able to do so. Only issue i am facing that my application is not able to connect to redis stream in ocp, while redis cache is working fine. help me how can i troubleshoot this.

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
