### ISSUE TITLE
Producing logs in JSON format

### ISSUE THREAD

**Issue by kuldeepsidhu88** [docker-library/redis#249]
I am ruuning redis:5 image. 
By default it produces logs in plaintext format.
Is their way we can wrap it up in JSON?
As docker logs are consumed by other systems like Elastic so JSON is the expected format.

If its not possible from the image, any idea how can I do it manually by writing some scripts etc which can consume the logs before and wrap it in JSON before spitting it out to Standard output?

**Comment by wglambert** [comment]
I don't think Redis can be configured to output logs in JSON format, but this elastic module looks like what you're wanting https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-redis.html

You could try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by kuldeepsidhu88** [comment]
@wglambert Thanks
