### ISSUE TITLE
ERR max number of clients reached

### ISSUE THREAD

**Issue by jonahbohlmann** [docker-library/redis#257]
Hello,

I have the default container and got the following error after some time: `ERR max number of clients reached`

I only use a simple NuGet Package in my dotnet core application:
`<PackageReference Include="BeetleX.Redis" Version="0.9.7.9" />`

Any ideas how to fix?

Thanks!

**Comment by wglambert** [comment]
The default is 10,000 so you could for instance either increase that, or shorten the connection timeout
```console
$ docker run -d --rm --name redis redis
56d530b87d08658dfccbe1fc728db52b1b8f5354dae81ab9a7b32d3fb1045b9c

$ docker exec -it redis bash
root@56d530b87d08:/data# redis-cli -h localhost -p 6379 config get maxclients
1) "maxclients"
2) "10000"
```

This seems relevant https://stackoverflow.com/questions/60370746/redis-error-max-number-of-clients-reached

But I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
