### ISSUE TITLE
Not using a configuration file is recommended only for development or testing purposes

### ISSUE THREAD

**Issue by x-yuri** [docker-library/redis#263]
> Redis is able to start without a configuration file using a built-in default configuration, however this setup is only recommended for testing and development purposes.

https://redis.io/topics/config

A couple more relevant links:

https://github.com/docker-library/redis/blob/f634377/6.0/alpine/Dockerfile#L40-L48
https://github.com/docker-library/redis/issues/4#issuecomment-50780840

**Comment by x-yuri** [comment]
Is there a reason not to use the [suggested configuration][1]?

[1]: https://redis.io/topics/config

**Comment by yosifkit** [comment]
We don't supply a "default" config file because that is up to users to define what values are appropriate for their deployment, and whether it is via a config file or [command line arguments](https://redis.io/topics/config#passing-arguments-via-the-command-line).

I would think their warning is that relying on the built-in default config could mean that if it changes in the future, it might break your usage, so you need to be explicit about your Redis server configuration.
