### ISSUE TITLE
Opening the temp file for AOF rewrite in rewriteAppendOnlyFile(): Permission denied

### ISSUE THREAD

**Issue by roman-blox** [docker-library/redis#265]
Running redis in docker on AWS cluster. 
Getting the following error:
```
Opening the temp file for AOF rewrite in rewriteAppendOnlyFile(): Permission denied
```

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by wenhao9295** [comment]
1:M 05 Feb 2021 12:12:39.427 # Background AOF rewrite terminated with error
1:M 05 Feb 2021 12:12:39.527 * Starting automatic rewriting of AOF on 7109782400% growth
1:M 05 Feb 2021 12:12:39.527 * Background append only file rewriting started by pid 962325
962325:C 05 Feb 2021 12:12:39.527 # Opening the temp file for AOF rewrite in rewriteAppendOnlyFile(): Permission denied

**Comment by wglambert** [comment]
There isn't enough information to attempt to troubleshoot the issue with just a `Permission denied` error to go by

If you could get a minimal reproducer that would help with probing the cause of it, but I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
