### ISSUE TITLE
 WARNING: Sentinel was not able to save the new configuration on disk!!!: Device or resource busy

### ISSUE THREAD

**Issue by startjava** [docker-library/redis#287]
sudo docker run -v /home/ghy/redis_master_replica/RedisSentinel1.conf:/redisConfig/RedisSentinel1.conf -v /home/ghy/redis_master_replica/sentinel_data:/sentinel_data --name redis6.2.5_sentinel_26381 --network host -d redis:6.2.5 redis-sentinel /redisConfig/RedisSentinel1.conf

log info bottom： 
1:X 28 Aug 2021 03:40:19.696 # Could not rename tmp config file (Device or resource busy)
1:X 28 Aug 2021 03:40:19.696 # WARNING: Sentinel was not able to save the new configuration on disk!!!: Device or resource busy

restart 3 sentinel server, 

use command:
info sentinel

show old master !

**Comment by startjava** [comment]
[ghy@localhost redis_master_replica]$ sudo docker -v
[sudo] ghy 的密码：
Docker version 20.10.8, build 3967b7d
[ghy@localhost redis_master_replica]$

**Comment by wglambert** [comment]
Something else might be using that file/directory. I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by yosifkit** [comment]
I would guess the problem is that the conf file is mounted directly (by inode) and when redis goes to save/edit it, then that will fail because the "idempotent" way to write a file is to write it to a temporary file and then rename to the real file and that won't work on a bind-mounted file.

Try mounting the directory of the config file instead. May want to make a "conf" sub-directory for it.
