### ISSUE TITLE
why : Can't open nodes-7771.conf in order to acquire a lock: Permission denied

### ISSUE THREAD

**Issue by startjava** [docker-library/redis#288]
sudo docker run -v /home/ghy/cluster:/redisConfig -v /home/ghy/cluster/data:/data --privileged=true --name redis6.2.5_master_7771 --network host -d redis:6.2.5 redis-server /redisConfig/redis-7771.conf

---------------------------------------------------------------

1:C 28 Aug 2021 06:43:36.061 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

1:C 28 Aug 2021 06:43:36.061 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started

1:C 28 Aug 2021 06:43:36.061 # Configuration loaded

1:M 28 Aug 2021 06:43:36.062 * monotonic clock: POSIX clock_gettime

1:M 28 Aug 2021 06:43:36.062 # Can't open nodes-7771.conf in order to acquire a lock: Permission denied

**Comment by startjava** [comment]
but i not want use  chomd the linux command for "cluster" dir!

**Comment by wglambert** [comment]
You need to adjust the permissions on `/redisConfig/redis-7771.conf` for the user (uid 999) running in the container, such as `chown 999 redis-7771.conf`

Also I would advise not running containers with privileged mode as it gives the container the same capabilities as the host https://containerjournal.com/topics/container-security/why-running-a-privileged-container-is-not-a-good-idea/
Coupled with the notes on security https://github.com/docker-library/docs/tree/master/redis#security
>`This means that if you expose the port outside of your host (e.g., via -p on docker run), it will be open without a password to anyone`

We've had a lot of issues crop up about redis instances becoming compromised https://github.com/docker-library/redis/issues/235 and this would be even more unfortunate with the container running as privileged

In the future questions like these should be asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
