### ISSUE TITLE
Missing config file

### ISSUE THREAD

**Issue by mirekphd** [docker-library/redis#300]
Redis [docs](https://redis.io/topics/config) state that:
_"Redis is able to start without a configuration file using a built-in default configuration, however this setup is only recommended for testing and development purposes. The proper way to configure Redis is by providing a Redis configuration file, usually called redis.conf."_

And yet the official Redis images lack any config files (not that I wasn't looking for them), relying on defaults hard-coded in the application, exposing users to a risk of config changes after each upgrade. Can you therefore bundle `redis.conf` with your flagship Alpine-based containers, containing appropriate defaults? This is what Bitnami is already doing with their Debian-based `bitnami/redis` containers.

**Comment by tianon** [comment]
Honestly, this is kind of intentional -- even if we embedded a default configuration file, we would update it any time upstream updates their defaults (which wouldn't really be the behavior you're looking for).  Our goal is to follow upstream's defaults and recommendations for deployment as closely as possible.

What I would suggest in your case is to create a short `Dockerfile` which is `FROM` this image and includes a hard-coded configuration file with the default values you expect.

**Comment by mirekphd** [comment]
> create a short `Dockerfile` which is `FROM` this image and includes a hard-coded configuration file with the default values you expect.

Very sound advice, which I also converged on when designing a stateless container for Redis acting as an K/V store (a write once, read-many database that should not try to write anything to disk). The config file I bundled with the external container was nearly empty, with only those parameters that needed to be changed from default values - such as the path to the RDB file and snapshotting parameters. You can see it in action as `mirekphd/ml-fs-db`.

You might also be interested why I did not consider using Bitnami's Redis containers that do contain complete config files? That was for security reasons - Alpine beats Debian easily when it comes to the severity and number of vulnerabilities.
