### ISSUE TITLE
WORKDIR should be different 

### ISSUE THREAD

**Issue by samkhamk** [docker-library/redis#321]
Hello Team,

can some one help how I can get below requirements

currently my docker has below parameters 
WORKDIR /red/data
VOLUME ["/red/data","/red/tmp"]

and append-only file stores under  /red/data/  location

**Requirement** 

I want WORKDIR should be only **/red** and append-only file stores under  **/red/data**

can you please let me know how I can configure gitlab-redis such way 

Regards,
SAM

**Comment by wglambert** [comment]
These repo's are for the Docker [Official Images](https://hub.docker.com/_/redis) and aren't related to gitlab-redis

I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
