### ISSUE TITLE
Security vulnerabilities [fedramp] related to redis 7 

### ISSUE THREAD

**Issue by jaawasth** [docker-library/redis#347]
Hello, 

We are seeing following vulnerabilities by fedramp scanner, would like to know when can we get a fix for those ?

```
#table cols="5"
Package Installed_Version Required_Version Language Install_Path
github.com/opencontainers/runc v1.1.0 1.1.2 Go usr/local/bin/gosu
```

Hash of the image

```
redis-7@sha256:e1294189c373797fe83307ab82fec233411bb035e1bb75f0dd8946dd08346295

**Comment by tianon** [comment]
Since this is specifically `gosu` related, see https://github.com/tianon/gosu/blob/master/SECURITY.md

(If you run `govulncheck` on the `gosu` binary, you'll likely see that the reported vulnerabilities don't apply to the built binary, and should be reported to the maintainers/vendor of the fedramp scanner as false positives.)

I'm not sure what `sha256:e1294189c373797fe83307ab82fec233411bb035e1bb75f0dd8946dd08346295` is -- it doesn't correspond to any manifest list, image manifest, config blob, or even layer blob that we've ever published. :confused:

**Comment by jaawasth** [comment]
@tianon , could be we are republishing to our internal acr, so it's changing
we are essentially just consuming in our redis dockerfile

```
FROM mcr.microsoft.com/mirror/docker/library/redis:7
```

Also, are you not getting reported for fedramp compliance ?
I'm not sure, even if there is a false reporting that needs to be done are the downstream teams expected to do that ?

**Comment by 4n4nd** [comment]
@tianon docker hub analysis is also complaining about the runc version [here](https://hub.docker.com/layers/library/redis/latest/images/sha256-a2b5e4899c5c9080c9c2b3c7c5b715e5db85286b9c243b8e5f77c38b8647b6b6?context=repo&tab=vulnerabilities).

**Comment by tianon** [comment]
The only `runc` in this image is the library embedded in `gosu` (of which no vulnerable code is actually invoked / included / compiled).

Additionally, we've since updated to `gosu` version 1.17 which switches from the `runc` library to the now-shared `github.com/moby/sys/user` (since `runc` wasn't actually using this functionality, so it was an odd place for that code to still live), which should help with the false positives in security scanning tools.
