### ISSUE TITLE
overcommit_memory

### ISSUE THREAD

**Issue by carstenlund** [docker-library/redis#349]
Hi there, I get this warning, and my site stops working.

I'm trying to follow the fix. I have access to my server through ssh, but when I try to access  /etc/sysctl.conf  Permission is denied.
-bash: /etc/sysctl.conf: Permission denied

I'm not experienced in Redis or SSH, but I can follow simple ssh commands.

How do I access /etc/sysctl.conf to fix the overcommit_memory issue?

Thanks!

WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. 

To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 25 Feb 2023 11:00:08.673 * Ready to accept connections

**Comment by wglambert** [comment]
Hey, these repos are for the Docker image of Redis https://github.com/docker-library/redis
Since this is outside of a container and on the host system, to get permission to modify that file you can use `sudo nano /etc/sysctl.conf`

I would also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)
