### ISSUE TITLE
is any docker image already available with BUILD_TLS

### ISSUE THREAD

**Issue by Anuradha-26** [docker-library/redis#367]
Hi,
I want to know if there is any docker image already available with BUILD_TLS=yes so that we need not clone the entire redis code and build again just for 1 parameter.
Also i want to know what is the overhead if redis itself would always build with BUILD_TLS=yes and if someone doesn't want TLS they would not provide the certificates.

**Comment by tianon** [comment]
I'm confused; we enable this in _all_ our images already: :sweat_smile:

https://github.com/docker-library/redis/blob/7e4a3dd9d2644458a40700a96620f6f028887a25/7.0/Dockerfile#L80

https://github.com/docker-library/redis/blob/7ef4e925387c9c4063b25e83928a85ff44dddf4d/7.0/alpine/Dockerfile#L65

(It's been included in our images since b6d413ceff3a2bca10a430ace121597fa8fe2a2c / #218 / 6.0-rc1, which is the first release that included this support :sweat_smile:)

**Comment by Anuradha-26** [comment]
Thanks so much @tianon , you made my day !
