### ISSUE TITLE
Use --userns-remap ?

### ISSUE THREAD

**Issue by trompx** [docker-library/redis#51]
Hello,

I was wondering if there is any reason to not use --userns-remap available since docker 1.10 ?

**Comment by tianon** [comment]
I don't see any reason why it wouldn't work, but perhaps I'm misunderstanding the question?  We support using `docker run --user ...` directly, and `--userns-remap` would work transparently at a higher level (since it's a daemon-level setting), so I don't think there's anything really to change here in the Redis repo unless there's something actually broken by using this.
