### ISSUE TITLE
Making the discontinued v2.8 alive again

### ISSUE THREAD

**Issue by ktogo** [docker-library/redis#73]
Hi,

I've found that you have discontinued 2.8 and removed it from Dockerhub.

I was actually using the version and still need it, because Amazon's AWS Elasticache still only supports version 2.6 towards 2.8.
http://docs.aws.amazon.com/ja_jp/AmazonElastiCache/latest/UserGuide/SelectEngine.html

Since they don't support 3x, I still need Redis 2x on Docker to synchronize the capability and functionality between Elasticache and my local testing/development facility built on Docker. 

Is it possible to turn 2.x back to alive?

Thanks

**Comment by yosifkit** [comment]
We've only removed our support for the images, since upstream no longer maintains that version.  This means that we do not rebuild them when the base Debian image changes.  The old images are still available to pull from the [docker hub](https://hub.docker.com/r/library/redis/tags/) and we don't foresee removing them.

**Comment by ktogo** [comment]
@yosifkit Ah I see. Sorry I thought that the discontinuation/removal also avoids any future pulls from Docker Hub. Just tried to pull it from Docker Hub and it succeeded properly. Thanks.
