### ISSUE TITLE
docker-entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by anyforever** [docker-library/redis#83]
![qq 20161117110913](https://cloud.githubusercontent.com/assets/787409/20374880/53914314-acb6-11e6-9891-7495de162ddb.png)

**Comment by tianon** [comment]
If you want to build the `Dockerfile`, you need to clone the repository or copy all necessary files manually (and set the necessary permissions on them) to ensure the full appropriate build context is available.

Any particular reason you're trying to build from source rather than using the pre-built images that are available?

**Comment by anyforever** [comment]
@tianon 
Thx.
