### ISSUE TITLE
Volume Mapping with custom redis.conf not working

### ISSUE THREAD

**Issue by Gamikoula** [docker-library/redis#90]
Hello,

i m trying to run a redis docker with a custom redis.conf 

i run this command but the redis container do not load my file. 

This is the Command:

docker run -v /data/redis.conf:/usr/local/etc/redis/redis.conf --name redis redis redis-server /usr/local/etc/redis/redis.conf

Maybe a Permissions Problem?

My data/redis.conf: root:root 644

**Comment by yu2003w** [comment]
You should specify directory rather than file path. Maybe this is the problem.

**Comment by MichelDiz** [comment]
I also have this issue.

Redis works perfectly inside the container, but when exposing the port to the host it is visible, but with this problem below. Medis does not report the error, but I believe it is the same thing because gives me a error. 

Doing the same process using the Redis-commaner stack (both Redis and commaner inside containers) does not work if I give the command below

Docker compose command: redis-server /usr/local/etc/redis/redis.conf
or

docker file CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

```
PS C:\Users\miche\Desktop\LAB\TEST> redis-commander
{ Error: ENOENT: no such file or directory, open 'C:\Users\miche\.redis-commander'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\miche\\.redis-commander' }
No config found or was invalid.
Using default configuration.
No Save: true
listening on  0.0.0.0 : 8081
Redis error Error: read ECONNRESET
    at _errnoException (util.js:1041:11)
    at TCP.onread (net.js:606:25)
No config found.
Using default configuration.
```

**Comment by tianon** [comment]
Indeed, this doesn't have enough information for us to reproduce, let alone help debug.  We'd need at least the contents of the configuration file and the logs of the container.  Also, in your example `docker run` line you're using `/data/redis.conf` as your host path, but I imagine your `data` directory isn't really directly at `/`, so you probably meant to use something more like `"$PWD/data/redis.conf"` to include the current directory in that host path.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
