### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by lesvere** [docker-library/redis#97]
```
docker run --name redis --restart=always \
-v /Users/lesvere/.docker/develop/config/redis.conf.default:/usr/local/etc/redis/redis.conf \
-p 6379:6379 \
-itd redis \
redis-server /usr/local/etc/redis/redis.conf
```

local(mac): `redis-cli -h 192.168.99.102 -p 6379`

```
Could not connect to Redis at 192.168.99.102:6379: Connection refused
```

**Comment by cihanb** [comment]
shouldn't you be doing this instead given "-p 6379:6379"
> redis-cli -h localhost -p 6379?

**Comment by lesvere** [comment]
exports port

run: docker run -P redis, only localhost.

thanks

**Comment by tianon** [comment]
When you use `docker run -P`, Docker will choose a random port.  What you wanted was `-p 6379:6379` instead, which will map the standard Redis port to the same port on your host.

Are you sure that `192.168.99.102` is the right IP for your VM?  Are you using Docker Toolbox or Docker for Mac?  (If you're using Docker Toolbox, you'll want to use `docker-machine ip` to determine the IP address of your VM, and if you're using Docker for Mac, you should be able to simply use `127.0.0.1`.)

Since this is an environmental issue, I'm going to close.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
